apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.lca.archive.configMapName }}
binaryData:
  {{ .Values.lca.archive.inventory.filename }}: {{ .Values.lca.archive.inventory.content | quote }}
